version: '3.8'

services:
  backend-app:
    image: 'sosna213/voting-app-backend:latest'
    container_name: backend-app
    ports:
      - "8180:8180"
    depends_on:
      - db
  db:
    image: 'postgres'
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  frontend:
    image: 'sosna213/voting-app-frontend:latest'
    ports:
      - "4200:4200"
    command: >
      bash -c "npm start"
